apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  labels:
    app: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
        - name: connect
          image: debezium/connect:2.5
          readinessProbe:
            httpGet:
              path: /
              port: 8083
          livenessProbe:
            httpGet:
              path: /
              port: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: GROUP_ID
              value: "1"
            - name: OFFSET_STORAGE_TOPIC
              value: connect-offsets
            - name: CONFIG_STORAGE_TOPIC
              value: connect-configs
            - name: STATUS_STORAGE_TOPIC
              value: connect-status
          ports:
          - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: connect
  labels:
    app: connect
spec:
  type: NodePort
  ports:
    - name: connect
      protocol: TCP
      port: 8083
  selector:
      app: connect